# Generated by Django 2.2 on 2019-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
